name: Build and Deploy

on:
    push:
        branches: ["master"]
    release:
        types: [published]
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write
    packages: write

jobs:
    

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup environment
              run: |
                  bash setup-extism.sh

            - name: Build
              run: |
                    npm i
                    npm run build

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: openagents-rag-coordinator-plugin
                  path: "./dist/"


            - name: Deploy to GitHub Releases
              if: github.event_name == 'release'
              run: |
                  set -e
                  echo "${GITHUB_EVENT_PATH}"
                  cat ${GITHUB_EVENT_PATH}
                  releaseId=$(jq --raw-output '.release.id' ${GITHUB_EVENT_PATH})

                  echo "Upload to release $releaseId"
                  for f in ./dist/*; do
                      echo "Uploading $f"
                      curl -L \
                      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Content-Type: application/zip" \
                      --data-binary @"$f" \
                      "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/$releaseId/assets?name=$(basename $f)"
                  done

                

                 
